# Generated by Django 5.0.14 on 2026-01-11 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_alter_usersubscription_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscription'),
        ),
    ]
