# Generated by Django 5.0.14 on 2026-01-11 06:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_subscriptionprice_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['order', 'featured', '-updated'], 'permissions': [('advanced', 'Advanced Perm'), ('pro', 'Pro Perm'), ('basic', 'Basic Perm'), ('basic-ai', 'Basic AI Perm')]},
        ),
        migrations.RemoveField(
            model_name='subscriptionprice',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='subscriptionprice',
            name='order',
        ),
        migrations.RemoveField(
            model_name='subscriptionprice',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='subscriptionprice',
            name='updated',
        ),
        migrations.AddField(
            model_name='subscription',
            name='featured',
            field=models.BooleanField(default=True, help_text='Featured on Django pricing page'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='order',
            field=models.IntegerField(default=-1, help_text='Orderding on django pricing page'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
