# Generated by Django 5.0.14 on 2026-01-11 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_alter_subscriptionprice_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='stripe_id',
            new_name='stripe_product_id',
        ),
        migrations.RenameField(
            model_name='subscriptionprice',
            old_name='stripe_id',
            new_name='stripe_price_id',
        ),
    ]
