# Generated by Django 5.0.14 on 2026-01-12 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0016_rename_stripe_id_subscription_stripe_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='stripe_product_id',
            new_name='stripe_id',
        ),
        migrations.RenameField(
            model_name='subscriptionprice',
            old_name='stripe_price_id',
            new_name='stripe_id',
        ),
    ]
